### ISSUE TITLE
certain endpoints result in crashes instead of a 401 response

### ISSUE THREAD

**Issue by danlugo92** [jhizzle84/api#26]
example: `connectpeer`

console:

```
{"time":"2019-10-18T14:32:16.391Z","ip":"192.168.1.181","method":"GET","path":"/api/lnd/transactions","query":{"paginate":"true","page":"1","itemsPerPage":"100"}}
validateToken err JsonWebTokenError: secret or public key must be provided
    at /home/daniel/workspace/api/node_modules/jsonwebtoken/verify.js:106:19
    at getSecret (/home/daniel/workspace/api/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/home/daniel/workspace/api/node_modules/jsonwebtoken/verify.js:94:10)
    at /home/daniel/workspace/api/services/auth/auth.js:56:27
    at new Promise (<anonymous>)
    at /home/daniel/workspace/api/services/auth/auth.js:54:14 {
  name: 'JsonWebTokenError',
  message: 'secret or public key must be provided'
}
(node:10577) UnhandledPromiseRejectionWarning: JsonWebTokenError: secret or public key must be provided
    at /home/daniel/workspace/api/node_modules/jsonwebtoken/verify.js:106:19
    at getSecret (/home/daniel/workspace/api/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/home/daniel/workspace/api/node_modules/jsonwebtoken/verify.js:94:10)
    at /home/daniel/workspace/api/services/auth/auth.js:56:27
    at new Promise (<anonymous>)
    at /home/daniel/workspace/api/services/auth/auth.js:54:14
(node:10577) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
{"time":"2019-10-18T14:32:48.004Z","ip":"192.168.1.114","method":"POST","path":"/api/lnd/auth","query":{}}
{"time":"2019-10-18T14:32:48.013Z","ip":"127.0.0.1","method":"GET","path":"/ping","query":{}}
mySocketsEvents.on(updateLightning
^C

```

**Comment by Emad-salah** [comment]
This issue is fixed with #54. Let me know if it occurs in any other route!
