### ISSUE TITLE
non-reported error on auth

### ISSUE THREAD

**Issue by danlugo92** [jhizzle84/api#31]
auth fails but theres no error message sent to consumer (i.e. no `errorMessage` o `message` on the response).

```
{"time":"2019-10-19T12:07:49.306Z","ip":"192.168.43.1","method":"POST","path":"/api/lnd/auth","query":{}}
Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/home/daniel/workspace/api/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/daniel/workspace/api/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/daniel/workspace/api/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/daniel/workspace/api/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/daniel/workspace/api/node_modules/grpc/src/client_interceptors.js:845:24) {
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses'
}
```

**Comment by Emad-salah** [comment]
This error usually occurs when not starting an LND server before firing up the API. I will add a friendly error message for that so it's clearer for the end-user.

**Comment by Emad-salah** [comment]
A fix for this issue has been pushed to master branch! d681b3c
